{
 "title": "Pizza Dashboard",
 "time": { "from": "now-20s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "targets": [
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "Pizza Purchases" },
    {
     "expr": "rate(pizza_creation_failures_total[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "rate(latency_pizza_creation_milliseconds_total[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_successful_total[1m])",
     "legendFormat": "Sucess"
    },
    { "expr": "rate(auth_failed_total[1m])", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "rate(latency_service_endpoint_milliseconds_total[1m])",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(revenue_USD_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 16 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Pizza Orders by HTTP Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 16 },
   "targets": [
    { "expr": "rate(requests_get_total[1m])", "legendFormat": "Get" },
    { "expr": "rate(requests_put_total[1m])", "legendFormat": "Put" },
    { "expr": "rate(requests_post_total[1m])", "legendFormat": "Post" },
    {
     "expr": "rate(requests_delete_total[1m])",
     "legendFormat": "Delete"
    },
    { "expr": "rate(requests_total[1m])", "legendFormat": "All" }
   ]
  }
 ]
}